# Generated by Django 2.2.5 on 2021-03-16 13:12

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('BudgetingApp', '0002_auto_20210316_0659'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('user_budget', models.IntegerField()),
            ],
            managers=[
                ('user', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='budgetinfo',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BudgetingApp.AccountInfo'),
        ),
    ]
