# Generated by Django 2.2.5 on 2021-03-17 01:41

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('BudgetingApp', '0003_auto_20210316_0712'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='accountinfo',
            managers=[
                ('account', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='budgetinfo',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='budgetinfo',
            name='expenses',
        ),
        migrations.RemoveField(
            model_name='budgetinfo',
            name='user',
        ),
        migrations.AddField(
            model_name='budgetinfo',
            name='expense_name',
            field=models.CharField(default='Expense Name', max_length=30),
        ),
        migrations.AddField(
            model_name='budgetinfo',
            name='username',
            field=models.CharField(default='Your Name!', max_length=20),
        ),
        migrations.AlterField(
            model_name='accountinfo',
            name='password',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='accountinfo',
            name='username',
            field=models.CharField(max_length=100),
        ),
    ]
