# Generated by Django 2.2.5 on 2020-12-15 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DestinationGoals', '0002_auto_20201211_2225'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='language',
            field=models.CharField(blank=True, default='', max_length=60),
        ),
        migrations.AlterField(
            model_name='destination',
            name='description',
            field=models.TextField(default='', max_length=300),
        ),
    ]
