# Generated by Django 2.2.5 on 2020-12-15 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DestinationGoals', '0004_auto_20201215_1900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='language',
            field=models.CharField(choices=[('English', 'English'), ('Spanish', 'Spanish'), ('French', 'French'), ('Russian', 'Russian'), ('Mandarin', 'Mandarin'), ('Korean', 'Korean'), ('German', 'German'), ('Italian', 'Italian'), ('Portuguese', 'Portuguese')], max_length=60),
        ),
        migrations.AlterField(
            model_name='destination',
            name='type',
            field=models.CharField(choices=[('City', 'City'), ('Country', 'Country'), ('State', 'State')], max_length=60),
        ),
    ]
