# Generated by Django 2.2.5 on 2020-11-19 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Indoor_Plant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plant_name', models.CharField(max_length=50)),
                ('plant_growth', models.CharField(choices=[('Trailing/Vining', 'Trailing/Vining'), ('Tree', 'Tree'), ('Shrub', 'Shrub'), ('Succulent', 'Succulent'), ('Fern', 'Fern')], max_length=25)),
                ('plant_light', models.CharField(choices=[('Direct Light', 'Direct Light'), ('Bright Indirect Light', 'Bright Indirect Light'), ('Indirect Light', 'Indirect Light')], max_length=30)),
                ('plant_description', models.TextField(max_length=300)),
            ],
        ),
    ]
