# Generated by Django 2.2.5 on 2021-02-18 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HikingFunApp', '0004_auto_20210217_1248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trails',
            name='difficulty',
            field=models.CharField(choices=[('easy', 'easy'), ('medium', 'medium'), ('hard', 'hard')], max_length=10),
        ),
        migrations.AlterField(
            model_name='trails',
            name='location',
            field=models.CharField(default='', max_length=40),
        ),
    ]
