# Generated by Django 2.2.5 on 2021-02-18 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HikingFunApp', '0005_auto_20210217_1845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trails',
            name='difficulty',
            field=models.CharField(choices=[('medium', 'medium'), ('hard', 'hard'), ('easy', 'easy')], max_length=10),
        ),
        migrations.AlterField(
            model_name='trails',
            name='location',
            field=models.CharField(default='', max_length=80),
        ),
    ]
