# Generated by Django 2.2.5 on 2021-02-18 19:08

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('UpcomingConcertsApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='conductor',
            managers=[
                ('conductors', django.db.models.manager.Manager()),
            ],
        ),
    ]
