# Generated by Django 2.2.5 on 2021-02-18 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UpcomingConcertsApp', '0002_auto_20210218_1208'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conductor',
            old_name='name',
            new_name='conductor_name',
        ),
        migrations.RenameField(
            model_name='orchestra',
            old_name='name',
            new_name='orchestra_name',
        ),
    ]
