# Generated by Django 2.2.5 on 2021-02-19 20:59

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('UpcomingConcertsApp', '0003_auto_20210218_1223'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='piece',
            managers=[
                ('pieces', django.db.models.manager.Manager()),
            ],
        ),
        migrations.RemoveField(
            model_name='concert',
            name='pieces',
        ),
        migrations.AddField(
            model_name='piece',
            name='concert_programs',
            field=models.ManyToManyField(to='UpcomingConcertsApp.Concert'),
        ),
    ]
