# Generated by Django 2.2.5 on 2021-02-19 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UpcomingConcertsApp', '0004_auto_20210219_1359'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='piece',
            name='concert_programs',
        ),
        migrations.AddField(
            model_name='concert',
            name='pieces',
            field=models.ManyToManyField(to='UpcomingConcertsApp.Piece'),
        ),
    ]
