# Generated by Django 2.2.5 on 2021-02-19 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UpcomingConcertsApp', '0006_concert_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concert',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
