# Generated by Django 2.2.5 on 2021-02-19 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UpcomingConcertsApp', '0007_auto_20210219_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concert',
            name='date',
            field=models.DateField(),
        ),
    ]
