# Generated by Django 2.2.5 on 2021-02-21 04:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UpcomingConcertsApp', '0009_auto_20210219_1651'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='concert',
            name='concert_date',
        ),
    ]
