# Generated by Django 2.2.5 on 2021-02-21 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UpcomingConcertsApp', '0010_remove_concert_concert_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='concert',
            name='concert_date',
            field=models.DateField(default=0.00023762376237623762),
            preserve_default=False,
        ),
    ]
