# Generated by Django 2.2.5 on 2021-02-21 04:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UpcomingConcertsApp', '0011_concert_concert_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='concert',
            old_name='concert_date',
            new_name='date',
        ),
    ]
