# Generated by Django 2.2.5 on 2021-02-21 04:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UpcomingConcertsApp', '0012_auto_20210220_2135'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='concert',
            name='date',
        ),
    ]
