# Generated by Django 2.2.5 on 2021-02-21 04:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UpcomingConcertsApp', '0013_remove_concert_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='concert',
            name='concert_date',
            field=models.DateField(default=datetime.date(2021, 2, 20)),
        ),
    ]
