# Generated by Django 2.2.5 on 2021-02-21 05:00

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('UpcomingConcertsApp', '0014_concert_concert_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concert',
            name='concert_date',
            field=models.DateField(default=datetime.datetime(2021, 2, 21, 5, 0, 2, 656092, tzinfo=utc)),
        ),
    ]
