# Generated by Django 2.2.5 on 2021-02-21 05:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('UpcomingConcertsApp', '0015_auto_20210220_2200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concert',
            name='concert_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
