# Generated by Django 2.2.5 on 2020-11-24 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AstronomyApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Planet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('planet_identification', models.CharField(max_length=50)),
                ('gravity', models.FloatField()),
                ('temperature', models.IntegerField(max_length=15)),
                ('atmosphere', models.CharField(choices=[('Hydrogen', 'Hydrogen'), ('Sulfuric Acid', 'Sulfuric Acid'), ('Oxygen/Nitrogen', 'Oxygen/Nitrogen'), ('Carbon dioxide', 'Carbon dioxide'), ('Methane/Ammonia', 'Methane/Ammonia'), ('None', 'None'), ('Unknown', 'Unknown')], max_length=50)),
                ('water', models.BooleanField(choices=[('Yes', 'Yes'), ('No', 'No'), ('Unknown', 'Unknown')], max_length=7)),
                ('magnetic_field', models.BooleanField(choices=[('Yes', 'Yes'), ('No', 'No'), ('Unknown', 'Unknown')], max_length=7)),
            ],
        ),
        migrations.DeleteModel(
            name='Person',
        ),
    ]
