# Generated by Django 2.2.5 on 2020-11-24 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AstronomyApp', '0002_auto_20201123_2154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planet',
            name='temperature',
            field=models.CharField(max_length=15),
        ),
    ]
