# Generated by Django 2.2.5 on 2020-12-01 23:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AstronomyApp', '0006_auto_20201129_1248'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='planet',
            managers=[
            ],
        ),
    ]
