# Generated by Django 2.2.5 on 2020-12-02 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AstronomyApp', '0007_auto_20201201_1840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planet',
            name='name',
            field=models.CharField(max_length=50, verbose_name='model verbose name'),
        ),
    ]
