# Generated by Django 2.2.5 on 2020-11-13 05:22

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CreatePlayer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
                ('age', models.IntegerField()),
                ('position', models.CharField(choices=[('Point Guard', 'Point Guard'), ('Shooting Guard', 'Shooting Guard'), ('Small Forward', 'Small Forward'), ('Power Forward', 'Power Forward'), ('Center', 'Center')], max_length=50)),
                ('weight', models.IntegerField()),
                ('years_pro', models.IntegerField()),
            ],
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
    ]
