# Generated by Django 2.2.5 on 2020-11-14 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=25)),
                ('last_name', models.CharField(max_length=50)),
                ('phone_number', models.CharField(blank=True, default='', max_length=10)),
                ('dish_name', models.CharField(choices=[('RastaPasta', 'RastaPasta'), ('CornSoup', 'CornSoup'), ('TaiNuggets', 'TaiNuggets'), ('SpicyTofuTacos', 'SpicyTofuTacos')], max_length=20)),
            ],
        ),
    ]
