# Generated by Django 2.2.5 on 2020-12-04 01:39

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Seafood',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=100)),
                ('harvested_during', models.DateField(blank=True)),
                ('wild_caught', models.BooleanField()),
            ],
            managers=[
                ('SeafoodIndex', django.db.models.manager.Manager()),
            ],
        ),
    ]
