# Generated by Django 2.2.5 on 2020-12-10 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cocktail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=60)),
                ('spirit', models.CharField(choices=[('vodka', 'vodka'), ('whiskey', 'whiskey'), ('tequila', 'tequila'), ('mezcal', 'mezcal'), ('gin', 'gin'), ('rum', 'rum'), ('other', 'other')], max_length=60)),
                ('ingredients', models.TextField(max_length=1000)),
                ('flavor_profile', models.CharField(choices=[('sweet', 'sweet'), ('sour', 'sour'), ('spicy', 'spicy'), ('bitter', 'bitter'), ('boozy', 'boozy')], max_length=200)),
                ('rating', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
            ],
        ),
    ]
