# Generated by Django 2.2.5 on 2020-11-25 05:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('code_language', models.CharField(choices=[('C#', 'C#'), ('Python', 'Python'), ('SQL', 'SQL'), ('JavaScript', 'JavaScript'), ('HTML', 'HTML')], default='Python', max_length=50, verbose_name='Code Language')),
                ('date_published', models.DateField(blank=True, null=True, verbose_name='Date Published')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CodeBookApp.Author')),
            ],
        ),
    ]
