# Generated by Django 2.2.5 on 2021-03-25 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CryptoApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='currency',
            name='launch_date',
        ),
        migrations.AddField(
            model_name='currency',
            name='launch_year',
            field=models.IntegerField(default=0),
        ),
    ]
