# Generated by Django 2.2.5 on 2020-12-10 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200)),
                ('type', models.CharField(max_length=60)),
                ('description', models.TextField(default='', max_length=300)),
                ('location', models.CharField(max_length=200)),
                ('price', models.CharField(max_length=60)),
            ],
        ),
    ]
