# Generated by Django 2.2.5 on 2020-12-10 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LABucketListApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='price',
            field=models.CharField(choices=[('Free', 'Free'), ('Under $25', 'Under $25'), ('$25 to $50', '$25 to $50'), ('$50 to $100', '$50 to $100'), ('$100+', '$100+')], max_length=60),
        ),
        migrations.AlterField(
            model_name='destination',
            name='type',
            field=models.CharField(choices=[('Site', 'Site'), ('Activity', 'Activity'), ('Food', 'Food'), ('Museum', 'Museum')], max_length=60),
        ),
    ]
