# Generated by Django 2.2.5 on 2020-11-24 18:41

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_title', models.CharField(max_length=60)),
                ('author', models.CharField(max_length=60)),
                ('published', models.CharField(max_length=60)),
                ('publisher', models.CharField(max_length=60)),
                ('followed_by', models.CharField(max_length=60)),
            ],
            managers=[
                ('Books', django.db.models.manager.Manager()),
            ],
        ),
    ]
