# Generated by Django 2.2.5 on 2020-11-24 23:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('street_address', models.CharField(max_length=150)),
                ('zip', models.IntegerField()),
                ('neighborhood', models.CharField(max_length=20)),
                ('type', models.CharField(choices=[('Bar', 'Bar'), ('Dance Club', 'Dance Club'), ('Lounge', 'Lounge')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dated', models.DateField()),
                ('title', models.CharField(max_length=25)),
                ('review', models.TextField(max_length=255)),
                ('rating', models.DecimalField(decimal_places=1, max_digits=2)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SeattleNightLife.Venue')),
            ],
        ),
    ]
