# Generated by Django 2.2.5 on 2020-11-25 02:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SeattleNightLife', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='review',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='venue',
            managers=[
            ],
        ),
    ]
