# Generated by Django 2.2.5 on 2021-04-20 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GuitarReviewsApp', '0004_auto_20210416_1153'),
        ('GuitarReviewsApp', '0004_auto_20210417_0254'),
    ]

    operations = [
    ]
