# Generated by Django 2.2.5 on 2021-04-19 03:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GuitarReviewsApp', '0004_auto_20210414_1750'),
        ('GuitarReviewsApp', '0004_auto_20210416_1153'),
    ]

    operations = [
    ]
