# Generated by Django 2.2.5 on 2021-04-22 01:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GuitarReviewsApp', '0005_merge_20210420_0529'),
        ('GuitarReviewsApp', '0004_auto_20210420_1643'),
    ]

    operations = [
    ]
