# Generated by Django 2.2.5 on 2021-02-25 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CampSite', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campsite',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='campsite',
            name='state',
            field=models.CharField(choices=[('OR', 'Oregon'), ('WA', 'Washington')], max_length=2),
        ),
        migrations.AlterField(
            model_name='mysite',
            name='state',
            field=models.CharField(choices=[('OR', 'Oregon'), ('WA', 'Washington')], max_length=2),
        ),
    ]
