# Generated by Django 2.2.5 on 2021-02-25 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CampSite', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campsite',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
