# Generated by Django 2.2.5 on 2021-02-25 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CampSite', '0002_auto_20210225_2136'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MySite',
        ),
    ]
