# Generated by Django 2.2.5 on 2021-02-26 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CampSite', '0003_delete_mysite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campsite',
            name='state',
            field=models.CharField(choices=[('OR', 'Oregon'), ('WA', 'Washington')], max_length=2),
        ),
    ]
